Version =20
VersionRequired =20
Begin Form
    RecordSelectors = NotDefault
    MaxButton = NotDefault
    MinButton = NotDefault
    ControlBox = NotDefault
    NavigationButtons = NotDefault
    CloseButton = NotDefault
    DividingLines = NotDefault
    FilterOn = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =11378
    DatasheetFontHeight =11
    ItemSuffix =2380
    Left =1920
    Top =1560
    Right =13620
    Bottom =11925
    Filter ="[AfdU]= '83_SOLISTTILB' AND [Year_]= 2026"
    RecSrcDt = Begin
        0xe58786140e2be640
    End
    RecordSource ="SELECT tblTilbudsSkabelon.A05, tblTilbudsSkabelon.A06, tblTilbudsSkabelon.A07, t"
        "blTilbudsSkabelon.A08, tblTilbudsSkabelon.A09, tblTilbudsSkabelon.E05, tblTilbud"
        "sSkabelon.E09, tblTilbudsSkabelon.D44, tblTilbudsSkabelon.G19, tblTilbudsSkabelo"
        "n.G20, tblTilbudsSkabelon.G21, tblTilbudsSkabelon.G22, tblTilbudsSkabelon.G23, t"
        "blTilbudsSkabelon.D19, tblTilbudsSkabelon.D20, tblTilbudsSkabelon.D21, tblTilbud"
        "sSkabelon.D22, tblTilbudsSkabelon.D23, tblTilbudsSkabelon.B23, tblTilbudsSkabelo"
        "n.B22, tblTilbudsSkabelon.B21, tblTilbudsSkabelon.B20, tblTilbudsSkabelon.B19, t"
        "blTilbudsSkabelon.A19, tblTilbudsSkabelon.A20, tblTilbudsSkabelon.A21, tblTilbud"
        "sSkabelon.A22, tblTilbudsSkabelon.A23, tblTilbudsSkabelon.F27, tblTilbudsSkabelo"
        "n.A27, tblTilbudsSkabelon.A28, tblTilbudsSkabelon.A29, tblTilbudsSkabelon.B29, t"
        "blTilbudsSkabelon.D29, tblTilbudsSkabelon.E28, tblTilbudsSkabelon.E39, tblTilbud"
        "sSkabelon.E40, tblTilbudsSkabelon.E41, tblTilbudsSkabelon.E42, tblTilbudsSkabelo"
        "n.E43, tblTilbudsSkabelon.F44, tblTilbudsSkabelon.E44, tblTilbudsSkabelon.D39, t"
        "blTilbudsSkabelon.D40, tblTilbudsSkabelon.D41, tblTilbudsSkabelon.D42, tblTilbud"
        "sSkabelon.D43, tblTilbudsSkabelon.E48, tblTilbudsSkabelon.E49, tblTilbudsSkabelo"
        "n.E50, tblTilbudsSkabelon.E51, tblTilbudsSkabelon.E52, tblTilbudsSkabelon.E53, t"
        "blTilbudsSkabelon.E57, tblTilbudsSkabelon.E58, tblTilbudsSkabelon.E59, tblTilbud"
        "sSkabelon.E63, tblTilbudsSkabelon.E64, tblTilbudsSkabelon.A68, tblTilbudsSkabelo"
        "n.B69, tblTilbudsSkabelon.A74, tblTilbudsSkabelon.E69, tblTilbudsSkabelon.D69, t"
        "blTilbudsSkabelon.E70, tblTilbudsSkabelon.E71, tblTilbudsSkabelon.E72, tblTilbud"
        "sSkabelon.E73, tblTilbudsSkabelon.E74, tblTilbudsSkabelon.E78, tblTilbudsSkabelo"
        "n.E79, tblTilbudsSkabelon.E83, tblTilbudsSkabelon.E87, tblTilbudsSkabelon.E88, t"
        "blTilbudsSkabelon.Kommentar, tblTilbudsSkabelon.A_Oms, tblTilbudsSkabelon.B_Over"
        "Underskud, tblTilbudsSkabelon.C_OverUnderPctOms, tblTilbudsSkabelon.I_Lønomk, tb"
        "lTilbudsSkabelon.J_OmkBest, tblTilbudsSkabelon.K_LønBorPer, tblTilbudsSkabelon.L"
        "_LønAdmTek, tblTilbudsSkabelon.M_OmkIkFast, tblTilbudsSkabelon.N_OmkKomp, tblTil"
        "budsSkabelon.O_LønOmkPctOms, tblTilbudsSkabelon.P_OmkKomPctOms, tblTilbudsSkabel"
        "on.Q_OmkAdmPctOms, tblTilbudsSkabelon.R_BorOmkPctOms, tblTilbudsSkabelon.S_EjdOm"
        "kPctOms, tblTilbudsSkabelon.Year_, tblTilbudsSkabelon.AfdU, tblTilbudsSkabelon.R"
        "evision FROM tblTilbudsSkabelon; "
    DatasheetFontName ="Calibri"
    RecordSource ="SELECT tblTilbudsSkabelon.A05, tblTilbudsSkabelon.A06, tblTilbudsSkabelon.A07, t"
        "blTilbudsSkabelon.A08, tblTilbudsSkabelon.A09, tblTilbudsSkabelon.E05, tblTilbud"
        "sSkabelon.E09, tblTilbudsSkabelon.D44, tblTilbudsSkabelon.G19, tblTilbudsSkabelo"
        "n.G20, tblTilbudsSkabelon.G21, tblTilbudsSkabelon.G22, tblTilbudsSkabelon.G23, t"
        "blTilbudsSkabelon.D19, tblTilbudsSkabelon.D20, tblTilbudsSkabelon.D21, tblTilbud"
        "sSkabelon.D22, tblTilbudsSkabelon.D23, tblTilbudsSkabelon.B23, tblTilbudsSkabelo"
        "n.B22, tblTilbudsSkabelon.B21, tblTilbudsSkabelon.B20, tblTilbudsSkabelon.B19, t"
        "blTilbudsSkabelon.A19, tblTilbudsSkabelon.A20, tblTilbudsSkabelon.A21, tblTilbud"
        "sSkabelon.A22, tblTilbudsSkabelon.A23, tblTilbudsSkabelon.F27, tblTilbudsSkabelo"
        "n.A27, tblTilbudsSkabelon.A28, tblTilbudsSkabelon.A29, tblTilbudsSkabelon.B29, t"
        "blTilbudsSkabelon.D29, tblTilbudsSkabelon.E28, tblTilbudsSkabelon.E39, tblTilbud"
        "sSkabelon.E40, tblTilbudsSkabelon.E41, tblTilbudsSkabelon.E42, tblTilbudsSkabelo"
        "n.E43, tblTilbudsSkabelon.F44, tblTilbudsSkabelon.E44, tblTilbudsSkabelon.D39, t"
        "blTilbudsSkabelon.D40, tblTilbudsSkabelon.D41, tblTilbudsSkabelon.D42, tblTilbud"
        "sSkabelon.D43, tblTilbudsSkabelon.E48, tblTilbudsSkabelon.E49, tblTilbudsSkabelo"
        "n.E50, tblTilbudsSkabelon.E51, tblTilbudsSkabelon.E52, tblTilbudsSkabelon.E53, t"
        "blTilbudsSkabelon.E57, tblTilbudsSkabelon.E58, tblTilbudsSkabelon.E59, tblTilbud"
        "sSkabelon.E63, tblTilbudsSkabelon.E64, tblTilbudsSkabelon.A68, tblTilbudsSkabelo"
        "n.B69, tblTilbudsSkabelon.A74, tblTilbudsSkabelon.E69, tblTilbudsSkabelon.D69, t"
        "blTilbudsSkabelon.E70, tblTilbudsSkabelon.E71, tblTilbudsSkabelon.E72, tblTilbud"
        "sSkabelon.E73, tblTilbudsSkabelon.E74, tblTilbudsSkabelon.E78, tblTilbudsSkabelo"
        "n.E79, tblTilbudsSkabelon.E83, tblTilbudsSkabelon.E87, tblTilbudsSkabelon.E88, t"
        "blTilbudsSkabelon.Kommentar, tblTilbudsSkabelon.A_Oms, tblTilbudsSkabelon.B_Over"
        "Underskud, tblTilbudsSkabelon.C_OverUnderPctOms, tblTilbudsSkabelon.I_Lønomk, tb"
        "lTilbudsSkabelon.J_OmkBest, tblTilbudsSkabelon.K_LønBorPer, tblTilbudsSkabelon.L"
        "_LønAdmTek, tblTilbudsSkabelon.M_OmkIkFast, tblTilbudsSkabelon.N_OmkKomp, tblTil"
        "budsSkabelon.O_LønOmkPctOms, tblTilbudsSkabelon.P_OmkKomPctOms, tblTilbudsSkabel"
        "on.Q_OmkAdmPctOms, tblTilbudsSkabelon.R_BorOmkPctOms, tblTilbudsSkabelon.S_EjdOm"
        "kPctOms, tblTilbudsSkabelon.Year_, tblTilbudsSkabelon.AfdU, tblTilbudsSkabelon.R"
        "evision FROM tblTilbudsSkabelon; "
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            BorderColor =8355711
            ForeColor =6710886
            FontName ="Calibri"
            GridlineColor =10921638
            ThemeFontIndex =1
            BorderTint =50.0
            ForeTint =60.0
            GridlineShade =65.0
        End
        Begin Image
            BackStyle =0
            OldBorderStyle =0
            BorderLineStyle =0
            SizeMode =3
            PictureAlignment =2
            Width =1701
            Height =1701
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin TextBox
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin FormHeader
            Height =0
            BackColor =13485442
            Name ="Formularhoved"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
        End
        Begin Section
            CanGrow = NotDefault
            Height =29650
            BackColor =14871513
            Name ="Detaljesektion"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            Begin
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =330
                    Width =8625
                    Height =630
                    FontSize =24
                    FontWeight =700
                    Name ="Label214"
                    Caption ="ØKONOMISKE NØGLETAL"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =330
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =960
                    LayoutGroup =1
                    BorderThemeColorIndex =0
                    ForeThemeColorIndex =0
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =330
                    Width =555
                    Height =630
                    Name ="EmptyCell91"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =330
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =960
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =330
                    Width =1815
                    Height =630
                    Name ="EmptyCell92"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =330
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =960
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =960
                    Width =8625
                    Height =285
                    Name ="EmptyCell82"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =960
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =1245
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =960
                    Width =555
                    Height =285
                    Name ="EmptyCell84"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =960
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =1245
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =960
                    Width =1815
                    Height =285
                    Name ="EmptyCell85"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =960
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =1245
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =8850
                    Width =8625
                    Height =300
                    Name ="EmptyCell2049"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =8850
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =9150
                    RowStart =30
                    RowEnd =30
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =8850
                    Width =555
                    Height =300
                    Name ="EmptyCell2051"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =8850
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =9150
                    RowStart =30
                    RowEnd =30
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =8850
                    Width =1815
                    Height =300
                    Name ="EmptyCell2052"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =8850
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =9150
                    RowStart =30
                    RowEnd =30
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =8550
                    Width =8625
                    Height =300
                    Name ="EmptyCell2054"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =8550
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =8850
                    RowStart =29
                    RowEnd =29
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =8550
                    Width =555
                    Height =300
                    Name ="EmptyCell2056"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =8550
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =8850
                    RowStart =29
                    RowEnd =29
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =8550
                    Width =1815
                    Height =300
                    Name ="EmptyCell2057"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =8550
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =8850
                    RowStart =29
                    RowEnd =29
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =1245
                    Width =8625
                    Height =285
                    Name ="Label2164"
                    Caption ="a)  Omsætning."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =1245
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =1530
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =1770
                    Width =8625
                    Height =300
                    Name ="Label2165"
                    Caption ="b)  Overskud/underskud."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =1770
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =2070
                    RowStart =4
                    RowEnd =4
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =2310
                    Width =8625
                    Height =300
                    Name ="Label2166"
                    Caption ="c)  Overskud/underskud opgjort i procent i forhold til omsætning."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =2310
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =2610
                    RowStart =6
                    RowEnd =6
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =2850
                    Width =8625
                    Height =300
                    Name ="Label2167"
                    Caption ="i)  Lønomkostninger til samlet ledelse."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =2850
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =3150
                    RowStart =8
                    RowEnd =8
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =3390
                    Width =8625
                    Height =300
                    Name ="Label2168"
                    Caption ="j)  Omkostninger til bestyrelseshonorarer."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =3390
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =3690
                    RowStart =10
                    RowEnd =10
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =3930
                    Width =8625
                    Height =300
                    Name ="Label2169"
                    Caption ="k)  Lønomkostninger til borgerrelateret personale."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =3930
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =4230
                    RowStart =12
                    RowEnd =12
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =4470
                    Width =8625
                    Height =300
                    Name ="Label2170"
                    Caption ="l)  Lønomkostninger til administrativt og teknisk personale."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =4470
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =4770
                    RowStart =14
                    RowEnd =14
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =5010
                    Width =8625
                    Height =300
                    Name ="Label2234"
                    Caption ="m)  Omkostninger til ikke-fastansat borgerrelateret personale"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =5010
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =5310
                    RowStart =16
                    RowEnd =16
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =5550
                    Width =8625
                    Height =300
                    Name ="Label2235"
                    Caption ="n)  Samlede omkostninger til kompetenceudvikling."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =5550
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =5850
                    RowStart =18
                    RowEnd =18
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =6090
                    Width =8625
                    Height =300
                    Name ="Label2237"
                    Caption ="o)  Samlede lønomkostninger opgjort i procent i forhold til omsætning."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =6090
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =6390
                    RowStart =20
                    RowEnd =20
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =6630
                    Width =8625
                    Height =300
                    Name ="Label2238"
                    Caption ="p)  Omkostninger til kompetenceudvikling opgjort i procent i forhold til omsætni"
                        "ng."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =6630
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =6930
                    RowStart =22
                    RowEnd =22
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =7170
                    Width =8625
                    Height =300
                    Name ="Label2239"
                    Caption ="q)  Samlede administrationsomkostninger opgjort i procent i forhold til omsætnin"
                        "gen."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =7170
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =7470
                    RowStart =24
                    RowEnd =24
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =7710
                    Width =8625
                    Height =300
                    Name ="Label2240"
                    Caption ="r)  Samlede borgerrelaterede omkostninger opgjort i procent i forhold til omsætn"
                        "ingen."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =7710
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =8010
                    RowStart =26
                    RowEnd =26
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    Left =360
                    Top =8250
                    Width =8625
                    Height =300
                    Name ="Label2241"
                    Caption ="s)  Ejendomsomkostninger opgjort i procent i forhold til omsætning."
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =8250
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =8550
                    RowStart =28
                    RowEnd =28
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =1245
                    Width =1815
                    Height =285
                    Name ="A_Oms"
                    ControlSource ="A_Oms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =1245
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =1530
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =1770
                    Width =1815
                    Height =300
                    TabIndex =1
                    Name ="B_OverUnderskud"
                    ControlSource ="B_OverUnderskud"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =1770
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =2070
                    RowStart =4
                    RowEnd =4
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =2310
                    Width =1815
                    Height =300
                    TabIndex =2
                    Name ="C_OverUnderPctOms"
                    ControlSource ="C_OverUnderPctOms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =2310
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =2610
                    RowStart =6
                    RowEnd =6
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =2850
                    Width =1815
                    Height =300
                    TabIndex =3
                    Name ="I_Lønomk"
                    ControlSource ="I_Lønomk"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =2850
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =3150
                    RowStart =8
                    RowEnd =8
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =3390
                    Width =1815
                    Height =300
                    TabIndex =4
                    Name ="J_OmkBest"
                    ControlSource ="J_OmkBest"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =3390
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =3690
                    RowStart =10
                    RowEnd =10
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =3930
                    Width =1815
                    Height =300
                    TabIndex =5
                    Name ="K_LønBorPer"
                    ControlSource ="K_LønBorPer"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =3930
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =4230
                    RowStart =12
                    RowEnd =12
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =4470
                    Width =1815
                    Height =300
                    TabIndex =6
                    Name ="L_LønAdmTek"
                    ControlSource ="L_LønAdmTek"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =4470
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =4770
                    RowStart =14
                    RowEnd =14
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =5010
                    Width =1815
                    Height =300
                    TabIndex =7
                    Name ="M_OmkIkFast"
                    ControlSource ="M_OmkIkFast"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =5010
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =5310
                    RowStart =16
                    RowEnd =16
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =5550
                    Width =1815
                    Height =300
                    TabIndex =8
                    Name ="N_OmkKomp"
                    ControlSource ="N_OmkKomp"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =5550
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =5850
                    RowStart =18
                    RowEnd =18
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =6090
                    Width =1815
                    Height =300
                    TabIndex =9
                    Name ="O_LønOmkPctOms"
                    ControlSource ="O_LønOmkPctOms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =6090
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =6390
                    RowStart =20
                    RowEnd =20
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =6630
                    Width =1815
                    Height =300
                    TabIndex =10
                    Name ="P_OmkKomPctOms"
                    ControlSource ="P_OmkKomPctOms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =6630
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =6930
                    RowStart =22
                    RowEnd =22
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =7170
                    Width =1815
                    Height =300
                    TabIndex =11
                    Name ="Q_OmkAdmPctOms"
                    ControlSource ="Q_OmkAdmPctOms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =7170
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =7470
                    RowStart =24
                    RowEnd =24
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =7710
                    Width =1815
                    Height =300
                    TabIndex =12
                    Name ="R_BorOmkPctOms"
                    ControlSource ="R_BorOmkPctOms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =7710
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =8010
                    RowStart =26
                    RowEnd =26
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    DecimalPlaces =2
                    OverlapFlags =87
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9540
                    Top =8250
                    Width =1815
                    Height =300
                    TabIndex =13
                    Name ="S_EjdOmkPctOms"
                    ControlSource ="S_EjdOmkPctOms"
                    Format ="Standard"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9540
                    LayoutCachedTop =8250
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =8550
                    RowStart =28
                    RowEnd =28
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =1245
                    Width =555
                    Height =285
                    Name ="EmptyCell2327"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =1245
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =1530
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =1770
                    Width =555
                    Height =300
                    Name ="EmptyCell2328"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =1770
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =2070
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =2310
                    Width =555
                    Height =300
                    Name ="EmptyCell2329"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =2310
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =2610
                    RowStart =6
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =2850
                    Width =555
                    Height =300
                    Name ="EmptyCell2330"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =2850
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =3150
                    RowStart =8
                    RowEnd =8
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =3390
                    Width =555
                    Height =300
                    Name ="EmptyCell2331"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =3390
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =3690
                    RowStart =10
                    RowEnd =10
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =3930
                    Width =555
                    Height =300
                    Name ="EmptyCell2332"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =3930
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =4230
                    RowStart =12
                    RowEnd =12
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =4470
                    Width =555
                    Height =300
                    Name ="EmptyCell2333"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =4470
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =4770
                    RowStart =14
                    RowEnd =14
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =5010
                    Width =555
                    Height =300
                    Name ="EmptyCell2334"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =5010
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =5310
                    RowStart =16
                    RowEnd =16
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =5550
                    Width =555
                    Height =300
                    Name ="EmptyCell2335"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =5550
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =5850
                    RowStart =18
                    RowEnd =18
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =6090
                    Width =555
                    Height =300
                    Name ="EmptyCell2336"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =6090
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =6390
                    RowStart =20
                    RowEnd =20
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =6630
                    Width =555
                    Height =300
                    Name ="EmptyCell2337"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =6630
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =6930
                    RowStart =22
                    RowEnd =22
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =7170
                    Width =555
                    Height =300
                    Name ="EmptyCell2338"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =7170
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =7470
                    RowStart =24
                    RowEnd =24
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =7710
                    Width =555
                    Height =300
                    Name ="EmptyCell2339"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =7710
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =8010
                    RowStart =26
                    RowEnd =26
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =8250
                    Width =555
                    Height =300
                    Name ="EmptyCell2340"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =8250
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =8550
                    RowStart =28
                    RowEnd =28
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =1530
                    Width =8625
                    Name ="EmptyCell2341"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =1530
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =1770
                    RowStart =3
                    RowEnd =3
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =1530
                    Width =555
                    Name ="EmptyCell2342"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =1530
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =1770
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =1530
                    Width =1815
                    Name ="EmptyCell2343"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =1530
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =1770
                    RowStart =3
                    RowEnd =3
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =2070
                    Width =8625
                    Name ="EmptyCell2344"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =2070
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =2310
                    RowStart =5
                    RowEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =2070
                    Width =555
                    Name ="EmptyCell2345"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =2070
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =2310
                    RowStart =5
                    RowEnd =5
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =2070
                    Width =1815
                    Name ="EmptyCell2346"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =2070
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =2310
                    RowStart =5
                    RowEnd =5
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =2610
                    Width =8625
                    Name ="EmptyCell2347"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =2610
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =2850
                    RowStart =7
                    RowEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =2610
                    Width =555
                    Name ="EmptyCell2348"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =2610
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =2850
                    RowStart =7
                    RowEnd =7
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =2610
                    Width =1815
                    Name ="EmptyCell2349"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =2610
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =2850
                    RowStart =7
                    RowEnd =7
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =3150
                    Width =8625
                    Name ="EmptyCell2350"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =3150
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =3390
                    RowStart =9
                    RowEnd =9
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =3150
                    Width =555
                    Name ="EmptyCell2351"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =3150
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =3390
                    RowStart =9
                    RowEnd =9
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =3150
                    Width =1815
                    Name ="EmptyCell2352"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =3150
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =3390
                    RowStart =9
                    RowEnd =9
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =3690
                    Width =8625
                    Name ="EmptyCell2353"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =3690
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =3930
                    RowStart =11
                    RowEnd =11
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =3690
                    Width =555
                    Name ="EmptyCell2354"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =3690
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =3930
                    RowStart =11
                    RowEnd =11
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =3690
                    Width =1815
                    Name ="EmptyCell2355"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =3690
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =3930
                    RowStart =11
                    RowEnd =11
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =4230
                    Width =8625
                    Name ="EmptyCell2356"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =4230
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =4470
                    RowStart =13
                    RowEnd =13
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =4230
                    Width =555
                    Name ="EmptyCell2357"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =4230
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =4470
                    RowStart =13
                    RowEnd =13
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =4230
                    Width =1815
                    Name ="EmptyCell2358"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =4230
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =4470
                    RowStart =13
                    RowEnd =13
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =4770
                    Width =8625
                    Name ="EmptyCell2359"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =4770
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =5010
                    RowStart =15
                    RowEnd =15
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =4770
                    Width =555
                    Name ="EmptyCell2360"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =4770
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =5010
                    RowStart =15
                    RowEnd =15
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =4770
                    Width =1815
                    Name ="EmptyCell2361"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =4770
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =5010
                    RowStart =15
                    RowEnd =15
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =5310
                    Width =8625
                    Name ="EmptyCell2362"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =5310
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =5550
                    RowStart =17
                    RowEnd =17
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =5310
                    Width =555
                    Name ="EmptyCell2363"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =5310
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =5550
                    RowStart =17
                    RowEnd =17
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =5310
                    Width =1815
                    Name ="EmptyCell2364"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =5310
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =5550
                    RowStart =17
                    RowEnd =17
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =5850
                    Width =8625
                    Name ="EmptyCell2365"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =5850
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =6090
                    RowStart =19
                    RowEnd =19
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =5850
                    Width =555
                    Name ="EmptyCell2366"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =5850
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =6090
                    RowStart =19
                    RowEnd =19
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =5850
                    Width =1815
                    Name ="EmptyCell2367"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =5850
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =6090
                    RowStart =19
                    RowEnd =19
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =6390
                    Width =8625
                    Name ="EmptyCell2368"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =6390
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =6630
                    RowStart =21
                    RowEnd =21
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =6390
                    Width =555
                    Name ="EmptyCell2369"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =6390
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =6630
                    RowStart =21
                    RowEnd =21
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =6390
                    Width =1815
                    Name ="EmptyCell2370"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =6390
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =6630
                    RowStart =21
                    RowEnd =21
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =6930
                    Width =8625
                    Name ="EmptyCell2371"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =6930
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =7170
                    RowStart =23
                    RowEnd =23
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =6930
                    Width =555
                    Name ="EmptyCell2372"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =6930
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =7170
                    RowStart =23
                    RowEnd =23
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =6930
                    Width =1815
                    Name ="EmptyCell2373"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =6930
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =7170
                    RowStart =23
                    RowEnd =23
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =7470
                    Width =8625
                    Name ="EmptyCell2374"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =7470
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =7710
                    RowStart =25
                    RowEnd =25
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =7470
                    Width =555
                    Name ="EmptyCell2375"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =7470
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =7710
                    RowStart =25
                    RowEnd =25
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =7470
                    Width =1815
                    Name ="EmptyCell2376"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =7470
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =7710
                    RowStart =25
                    RowEnd =25
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =360
                    Top =8010
                    Width =8625
                    Name ="EmptyCell2377"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =8010
                    LayoutCachedWidth =8985
                    LayoutCachedHeight =8250
                    RowStart =27
                    RowEnd =27
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =8985
                    Top =8010
                    Width =555
                    Name ="EmptyCell2378"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8985
                    LayoutCachedTop =8010
                    LayoutCachedWidth =9540
                    LayoutCachedHeight =8250
                    RowStart =27
                    RowEnd =27
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =9540
                    Top =8010
                    Width =1815
                    Name ="EmptyCell2379"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9540
                    LayoutCachedTop =8010
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =8250
                    RowStart =27
                    RowEnd =27
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
            End
        End
        Begin FormFooter
            Height =0
            BackColor =4074796
            Name ="Formularfod"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
        End
    End
End
